version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lunaflow_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lunaflow_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: lunaflow_keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: auth.soultechwebdesign.com.br
      KC_PROXY: edge
    volumes:
      # Mapeia sua pasta local de temas para dentro do Keycloak
      - ./infra/keycloak/themes:/opt/keycloak/themes
    depends_on:
      - postgres
    networks:
      - lunaflow_net
      - shield_net

networks:
  lunaflow_net:
    driver: bridge
  shield_net:
    external: true
    name: infra_shield_network

volumes:
  postgres_data:
